### PR TITLE
Scope `npx` to `git-mob` package

### PR DESCRIPTION
**Pull request by rkotze**
This commit scopes `npx` commands to `--package=git-mob`. Otherwise, if you have other packages with `git` binaries, the call to `npx` is ambiguous and it fails.

### CODE REVIEW

**Comment by rkotze** [comment]
@wycats Thanks for the PR.

I've tried it out and noticed that running the commands was very slow. Looks like every time a command is run `npx` re-installs `git-mob`. Not sure how to make it use the already installed package. I've used the `--no-install` flag in conjunction with `--package` but it seems to ignore it.

Perhaps you know of a way to prevent the install happening every time? If not, maybe there is another way to solve the issue you're trying fix.

**Comment by wycats** [comment]
@rkotze interesting. I also noticed the slowness but didn't put two and two together.

**Comment by wycats** [comment]
Maybe we could avoid using npx and just manage our own little sandbox somewhere?

**Comment by rkotze** [comment]
Sounds like an interesting idea. How would you go about making that sand box?

**Comment by yurifrl** [comment]
I'm having this issue for some reason, I have no other installed package `npx --package=git-mob git mob -v` works fine, It seems if this PR is merged it should fix it

image

**Comment by lalten** [comment]
I'm facing the same problem

would be great to get this fixed.

**Comment by rkotze** [comment]
@lalten @yurifrl - the problem with this solution is it will download the package every time the command is run. Making it very slow when using the UI.

If you install git-mob globally it should solve this issue as another option. `npm i -g git-mob`

**Comment by yurifrl** [comment]
@rkotze I have git-mob installed locally but it seems it's not accessible from vscode, maybe its because I use asdf, not sure, If I remember correctly I tried installing without asdf, a config that allowed us to pass the executable path would help in that case

**Comment by lalten** [comment]
@rkotze I did have git-mob installed globally at the time of above screenshot. I had also tried uninstalling and reinstalling, to no avail.

**Comment by rkotze** [comment]
Couple of things to check:

It might be worth checking npm and npx have the same major version, if not, it can cause this issue.

If you're using a node version manager like nvm, make sure you're installing git mob under the same node version as your project.

**Comment by rkotze** [comment]
Hi,

I've removed the need for Git Mob CLI and should fix the above issues in the latest version [1.13.0](https://github.com/rkotze/git-mob-vs-code/releases/tag/v1.13.0).

Please do give it a try when you get a chance. It should work as shown in the read me and still sync with Git Mob CLI if you want to use both.

I will close the PR. Thanks for your feedback.

**Pull request closed without merging**
