### PR TITLE
Added Toggle sort order command

### PR DESCRIPTION
**Pull request by viperet**
This PR adds the ability to toggle authors' sort order. (https://github.com/rkotze/git-mob-vs-code/issues/73)

### CODE REVIEW

**Review by rkotze — CHANGES_REQUESTED** [review]
Please see the [previous comment](https://github.com/rkotze/git-mob-vs-code/pull/74#issuecomment-954882141) and a couple of [unit tests failing](https://dev.azure.com/TinkerTaylor/VS%20code%20extensions/_build/results?buildId=297&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=29) to fix.

**Comment by viperet** [comment]
@rkotze sure, will fix that. Do you prefer parameter in the settings or icon in the sidebar to set sorting order?

**Comment by rkotze** [comment]
@viperet could you make it a setting, please?

**Comment by viperet** [comment]
Yes, sure. I’m on vacation now, will return in a week and change this PR according to your request

**Comment by viperet** [comment]
@rkotze I moved sorting direction to extension configuration and fixed tests.

**Review by rkotze — COMMENTED** [review]
This looks great 👍 @viperet 
One small thing, could you update the readme with information about the [setting](https://github.com/rkotze/git-mob-vs-code#settings), please?

**Comment by viperet** [comment]
@rkotze done

**Review by rkotze — APPROVED** [review]
Thanks @viperet

**Pull request merged**
